image: ubuntu

pages:
  stage: deploy
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt update
    - DEBIAN_FRONTEND=noninteractive apt -y make
  script:
  - make gnome-pages
  artifacts:
    paths:
    - public
  only:
  - master
